### ISSUE TITLE
Method labeled() always returns true

### ISSUE THREAD

**Issue by arhimed2t** [briandfoy/set-crossproduct#4]
Hello!
I found issue method labeled() always returns true:
**`$perl -MSet::CrossProduct -e '$z = Set::CrossProduct->new({one => [1], two => [2]}); print $z->labeled() ? "YES\n" : "NO\n" '`**
prints "YES", it is correct.
**`perl -MData::Dumper -MSet::CrossProduct -e '$z = Set::CrossProduct->new([ [1], [2] ]); print $z->labeled() ? "YES\n" : "NO\n" '`**
prints "YES" too, that is not correct.
Studiing code I found in costructor (Set/CrossProduct.pm line# 185):
```
        if( $ref_type eq ref {} ) {
                $self->{labeled} = 1;
                $self->{labels}  = [ sort keys %$constructor_ref ];
                $self->{arrays}  = [ @$constructor_ref{ sort keys %$constructor_ref } ];
                }
        elsif( $ref_type eq ref [] ) {
                $self->{labeled} = 1;
                $self->{arrays}  = $constructor_ref;
                }
```
Where $self->{labeled} always sets to 1 despite type of passed reference.

**Comment by briandfoy** [comment]
Good catch! I've fixed this in cb459b898a024f1bf707cf1a0448898447660eb8 and it will be part of the next release.
